# This is a basic workflow to help you get started with Actions
name: First Workflow

on: workflow_dispatch

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Run a one-line script
          run: echo "Hello, world!"
