# This is a basic workflow to help you get started with Actions
name: First Workflow
on: workflow_dispatch
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
       - name: Print greeting
         run: echo "Hello, world!"
         
       - name: Print greetings at a time
         run: |
          echo "Hello Guys"
          echo "Enjoy you Day!"
